### ISSUE TITLE
Issue with home_wifi_multi.h: No such file or directory

### ISSUE THREAD

**Issue by NorwinA** [arkhipenko/esp32-cam-mjpeg-multiclient#1]
I was getting the error 
home_wifi_multi.h: No such file or directory
what do I need to do?

![issues with ESPmulti](https://user-images.githubusercontent.com/63750817/82346172-21ec5e80-99c4-11ea-8564-eade07aab2b2.JPG)
![ESP32 streaming library](https://user-images.githubusercontent.com/63750817/82346219-316ba780-99c4-11ea-9e92-1e70fa6d4c35.JPG)

**Comment by arkhipenko** [comment]
This is an include with my home wifi credentials - obviously I have not included it...
This is what you need to do:

1. Create a file called "home_wifi_multi.h" in the same folder   OR   under a separate subfolder of the "libraries" folder of Arduino IDE. (You are creating a "fake" library really - I called it "MySettings"). 
2. Place the following text in the file:
#define SSID1 "replace with your wifi ssid"
#define PWD1 "replace your wifi password"
3. Save.

Should work then.
