### ISSUE TITLE
Does not work on AI Thinker ESP32-cam

### ISSUE THREAD

**Issue by bortek** [arkhipenko/esp32-cam-mjpeg-multiclient#15]
I am getting this in the serial output and the camera restarts.

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:1344
load:0x40078000,len:13864
load:0x40080400,len:3608
entry 0x400805f0
E (1476) gpio: gpio_set_level(226): GPIO output gpio_num error
E (1486) gpio: gpio_set_level(226): GPIO output gpio_num error
E (1508) camera: Camera probe failed with error 0x105(ESP_ERR_NOT_FOUND)
Error initializing the camera
ets Jun  8 2016 00:22:57

Camera is NOT faulty, just tested a cam web server and that code works

**Comment by arkhipenko** [comment]
Did you adjust the sketch to work with AI Thinker Cam?

#define CAMERA_MODEL_AI_THINKER

By default the sketch is set to work with ESP-EYE cam.

**Comment by bortek** [comment]
Oh my bad, I have missed that. Thanks for pointing it out :)
