### ISSUE TITLE
Wondering - could this be adapted to be able to stream to multiple connections use web

### ISSUE THREAD

**Issue by cgmckeever** [arkhipenko/esp32-cam-mjpeg-multiclient#2]
Hi! - found your project when looking for ways to stream to multiple clients using a standard web browser. 
Im currently basing much of my work off the [CameraWebServer example](https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/Camera/CameraWebServer/app_httpd.cpp#L305). Any pointers/guidance on where I could make use of your ideas would be great. 

Thanks

**Comment by arkhipenko** [comment]
Unfortunately, I am not using the SDK version of the camera streaming service. 

The idea, if you are up to bravely changing their code, is to keep track of all connected clients and serve frames to them either one after the other or in parallel using a dedicated RTOS task.  
Their solution also streams with "chunked" responses, that are for some reason disliked by VLC, hence my modifications.

This code, however, is capable of streaming to multiple browser windows. 
https://youtu.be/bsAVJSZeSmc
