### ISSUE TITLE
multiclient and LED flash on ESP32 cam

### ISSUE THREAD

**Issue by TungstenE2** [arkhipenko/esp32-cam-mjpeg-multiclient#6]
Hi all,

thx for this project!

I also found a nice project in order to be able to use the LED flash light.
https://github.com/xenpac/ESP32-CAM-with-LED-control

Is it possible to combine both projects?

Could somebody point me to the right tutorial in order to have both projects working on the ESP32 cam?
I am new to ESP32 and Arduino IDE.

thx for your support!

**Comment by arkhipenko** [comment]
This project uses streaming in parallel to doing other stuff.

https://www.hackster.io/anatoli-arkhipenko/minecraft-interactive-do-not-enter-sword-sign-esp32-cam-cd1b07
