### ISSUE TITLE
features

### ISSUE THREAD

**Issue by mplaxman** [arkhipenko/esp32-cam-mjpeg-multiclient#8]
hi i want use esp eye as realtime face recognization can i use this ?

if yes how to train bulk images in this ? is it possible to train the model in esp eye or we need train the model in server ?

we need some help if u give it is very helpful for me

**Comment by arkhipenko** [comment]
Face recognition was not part of this project, sorry.
That would be a separate project.

**Comment by mplaxman** [comment]
we know we are  asking suggestion if u have any information please share

**Comment by arkhipenko** [comment]
Unfortunately not. This could be a good paid research project though if you are interested.

**Comment by mplaxman** [comment]
what are the charges for this project ?

**Comment by arkhipenko** [comment]
Let's move this conversation to the email please. Send me a direct email to arkhipenko@hotmail.com
