### ISSUE TITLE
Video streaming with LAN network

### ISSUE THREAD

**Issue by quockhanh1198** [arkhipenko/esp32-cam-mjpeg-multiclient#9]
Hi @arkhipenko , firstly, thanks for your project. It was a really good and useful project for me. And I want to stream with LAN network, Can you help me, pls???, I set 2 modes (WLAN and AP mode) but LAN mode I can't set.

**Comment by arkhipenko** [comment]
I am not sure why - it works well on my end. You need to provide your WiFi credentials and connect to your router of course, then note the IP address on the Serial output (or on the router) and connect to it.
